[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/share-result/*"
  to = "/.netlify/functions/share-result"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 